/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    Chips: typeof import('primevue/chips')['default']
    CopyWrapper: typeof import('./src/components/CopyWrapper.vue')['default']
    Empty: typeof import('./src/components/Empty.vue')['default']
    Fill: typeof import('./src/components/Fill.vue')['default']
    FixedInputContainer: typeof import('./src/components/Subnetting/FixedInputContainer.vue')['default']
    Hotkey: typeof import('./src/components/Hotkey.vue')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    InputContainer: typeof import('./src/components/Subnetting/InputContainer.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    IpAddressInput: typeof import('./src/components/IpAddressInput.vue')['default']
    Lock: typeof import('./src/components/Lock.vue')['default']
    Message: typeof import('primevue/message')['default']
    PoweredByVue: typeof import('./src/components/PoweredByVue.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screen: typeof import('./src/components/Screen.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Slider: typeof import('primevue/slider')['default']
    SubnetItem: typeof import('./src/components/Subnetting/SubnetItem.vue')['default']
    SubnetMaskInput: typeof import('./src/components/SubnetMaskInput.vue')['default']
    SubnetOutput: typeof import('./src/components/Subnetting/SubnetOutput.vue')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    VariableInputContainer: typeof import('./src/components/Subnetting/VariableInputContainer.vue')['default']
    VirtualScroller: typeof import('primevue/virtualscroller')['default']
  }
  export interface ComponentCustomProperties {
    KeyFilter: typeof import('primevue/keyfilter')['default']
    Ripple: typeof import('primevue/ripple')['default']
  }
}
